### ISSUE TITLE
[BUG] <enter> in message breaks payment process

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/tipjar#9]
https://github.com/lnbits/tipjar/assets/63317640/e2af0588-d8d2-473f-bad8-8fa735a0fa32

surely not only in tipjar but untested elsewhere

**Comment by dni** [comment]
@talvasconcelos can you take a look? new lines in message seems to not work

**Comment by talvasconcelos** [comment]
Fixed on Satspay, next release 0.3.2

**Comment by arbadacarbaYK** [comment]
The bug report was for tipjar not satspay
